### ISSUE TITLE
Update CirrOS 0.5.2 kernel image to a supported version (kernel-5.4; from Focal)

### ISSUE THREAD

**Issue by kashyapc** [cirros-dev/cirros#102]
The current CirrOS 0.5.2 image is running the kernel `5.3.0-26-generic` . Two problems with it: (a) it is causing a guest kernel crash in OpenStack CI[1]; and more importantly, (b) it is based on an now-unsupported Ubuntu kernel.

One of the Ubuntu kernel maintainers gave this diagnosis in this bug[1]:

    "So this is a crash of the guest kernel from a CirrOS 0.5.2 image. 
    That image contains a 5.3 kernel which is no longer supported. The
    0.5.2 image is a minor update of the original 0.5.1 image which was
    built before the release of Focal. It was pulling in the HWE kernel 
    which at that time was a 5.3 kernel. The updated 0.5.2 CirrOS image
    apparently didn't upgrade the kernel hence it's also on an
    unsupported 5.3 kernel.

    "The current (supported) Bionic HWE kernel is 5.4 (same version as
    the Focal release kernel)."

[1] " Guest kernel crashes with GPF on volume attach" — https://bugs.launchpad.net/nova/+bug/2018612

---

Please refresh the CirrOS 0.5.2 image with the kernel  **5.4.0-148.165** (or higher) from "Focal" release.  This (kernel-5.4) is  LTS (long term support) kernel now.

**Comment by smoser** [comment]
It'd be nice to have you test output of the build for #103 
See https://github.com/cirros-dev/cirros/actions/runs/4917496313?pr=103

you can download one of the per-arch zip files and use those to test.

**Comment by smoser** [comment]
fixed. please open if you think not.

**Comment by osfrickler** [comment]
Did you re-publish the 0.5.2 release from this build? I not, we would likely want to do a 0.5.3?

**Comment by smoser** [comment]
yes, we want to do a 0.5.3.

**Comment by hrw** [comment]
0.5.3 uses 5.4.0-148.165~18.04.1 kernel.
