### ISSUE TITLE
Cirros image does not configure MTU according to DHCP

### ISSUE THREAD

**Issue by fwiesel** [cirros-dev/cirros#112]
It seems the `10-mtu` is usually included in other distributions (debian based at least).
Copied in plain-text it is just these lines.

```bash

# Configure the MTU for the interface
if [ -n "${new_interface_mtu}" ]; then
	ifconfig "${interface}" mtu "${new_interface_mtu}"
fi
```

**Comment by osfrickler** [comment]
I still cannot reproduce this. Can you share the output of `openstack network show` for your network and then `dhcpcd -U eth0`, `ip a` and `cirros-status` from your instance?

**Comment by fwiesel** [comment]
Okay, I have now a KVM hypervisor and there it looks like it should. I'll close it, until I can reproduce it.
