### ISSUE TITLE
Use Sudo less

### ISSUE THREAD

**Issue by hrw** [cirros-dev/cirros#21]
Now whole bundle runs with sudo. This leaves several root owned files. Which makes problem on Travis CI.

**Comment by smoser** [comment]
My last commit pull request #19 changed to run bin/build-release without sudo.
I poorly snuck that in without comment in cf543a9315f801a42c7ebce08a5dea69951439ff .

**Comment by hrw** [comment]
It was done here: a2a1113 (hrw/travis-cache, travis-cache) travis: no need for sudo everything

Whole bin/bundle is run with sudo - maybe there we should move use of sudo to things that needs it.
