### ISSUE TITLE
publish artifacts of daily builds somewhere.

### ISSUE THREAD

**Issue by smoser** [cirros-dev/cirros#22]
Ideally we'd publish artifacts of daily builds and pull request builds somewhere.
That would make checking things out easier.

**Comment by hrw** [comment]
https://docs.travis-ci.com/user/deployment/releases/#draft-releases-with-draft-true could be it.

Resulting files land in releases but are visible only to contributors. 

Check https://github.com/hrw/cirros/releases/tag/untagged-d438b3eea49c6da452d3 as an example - it is my draft build. Should not be visible in private mode browser.

**Comment by hrw** [comment]
https://docs.travis-ci.com/user/deployment#pull-requests

"Pull Requests #

Note that pull request builds skip the deployment step altogether."

So no way.
