### ISSUE TITLE
Do not warn on failure to load builtin modules.

### ISSUE THREAD

**Issue by smoser** [cirros-dev/cirros#23]
We are doing a boot test of images in  c-i now (thanks hrw).  Looking at logs
from a recent master build
(https://travis-ci.com/cirros-dev/cirros/builds/145698266) we see missing
modules:

 * [aarch64](https://travis-ci.com/cirros-dev/cirros/builds/145698266)
 * [x86_64](https://api.travis-ci.com/v3/job/279134394/log.txt)

I'm no sure how long logs live on travis, so these links might go missing.
Here is a section in the boot of 4.4.0-148.174.

    info: initramfs: up at 2.40
    modprobe: module qemu_fw_cfg not found in modules.dep
    modprobe: module virtio_blk not found in modules.dep
    modprobe: module virtio_net not found in _modules.dep_
    modprobe: module virtio_pci not found in modules.dep
    modprobe: module vfat not found in modules.dep
    modprobe: module nls_cp437 not found in modules.dep
    modprobe: module nls_iso8859-1 not found in modules.dep
    modprobe: module cdrom not found in modules.dep
    modprobe: module sr_mod not found in modules.dep
    modprobe: module sg not found in modules.dep
    WARN: /etc/rc3.d/S10-load-modules failed

I'm guessing that `grab-kernels` is not getting all the kernel packages. From
Ubuntu's kernel package page
([linux](https://launchpad.net/ubuntu/+source/linux)), we see the following
packages for current 4.4.  I've removed 'udeb' and dbgsym packages.

    linux-cloud-tools-4.4.0-21-generic_4.4.0-21.37_amd64.deb (1.7 KiB)
    linux-cloud-tools-4.4.0-21-generic_4.4.0-21.37_i386.deb (1.7 KiB)
    linux-cloud-tools-4.4.0-21-lowlatency_4.4.0-21.37_amd64.deb (1.7 KiB)
    linux-cloud-tools-4.4.0-21-lowlatency_4.4.0-21.37_i386.deb (1.7 KiB)
    linux-cloud-tools-4.4.0-21_4.4.0-21.37_amd64.deb (29.1 KiB)
    linux-cloud-tools-4.4.0-21_4.4.0-21.37_i386.deb (28.4 KiB)
    linux-cloud-tools-common_4.4.0-21.37_all.deb (23.1 KiB)
    linux-doc_4.4.0-21.37_all.deb (10.7 MiB)
    linux-headers-4.4.0-21-generic-lpae_4.4.0-21.37_armhf.deb (770.5 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_amd64.deb (761.7 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_arm64.deb (735.8 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_armhf.deb (778.0 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_i386.deb (745.6 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_ppc64el.deb (964.8 KiB)
    linux-headers-4.4.0-21-generic_4.4.0-21.37_s390x.deb (424.6 KiB)
    linux-headers-4.4.0-21-lowlatency_4.4.0-21.37_amd64.deb (758.7 KiB)
    linux-headers-4.4.0-21-lowlatency_4.4.0-21.37_i386.deb (742.5 KiB)
    linux-headers-4.4.0-21-powerpc-e500mc_4.4.0-21.37_powerpc.deb (858.3 KiB)
    linux-headers-4.4.0-21-powerpc-smp_4.4.0-21.37_powerpc.deb (840.2 KiB)
    linux-headers-4.4.0-21-powerpc64-emb_4.4.0-21.37_powerpc.deb (928.9 KiB)
    linux-headers-4.4.0-21-powerpc64-smp_4.4.0-21.37_powerpc.deb (945.8 KiB)
    linux-headers-4.4.0-21_4.4.0-21.37_all.deb (9.5 MiB)
    linux-image-4.4.0-21-generic-lpae_4.4.0-21.37_armhf.deb (55.5 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_amd64.deb (17.8 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_arm64.deb (52.1 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_armhf.deb (56.9 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_i386.deb (16.6 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_ppc64el.deb (17.7 MiB)
    linux-image-4.4.0-21-generic_4.4.0-21.37_s390x.deb (11.6 MiB)
    linux-image-4.4.0-21-lowlatency_4.4.0-21.37_amd64.deb (55.0 MiB)
    linux-image-4.4.0-21-lowlatency_4.4.0-21.37_i386.deb (53.4 MiB)
    linux-image-4.4.0-21-powerpc-e500mc_4.4.0-21.37_powerpc.deb (50.5 MiB)
    linux-image-4.4.0-21-powerpc-smp_4.4.0-21.37_powerpc.deb (49.0 MiB)
    linux-image-4.4.0-21-powerpc64-emb_4.4.0-21.37_powerpc.deb (54.5 MiB)
    linux-image-4.4.0-21-powerpc64-smp_4.4.0-21.37_powerpc.deb (57.0 MiB)
    linux-image-extra-4.4.0-21-generic_4.4.0-21.37_amd64.deb (37.0 MiB)
    linux-image-extra-4.4.0-21-generic_4.4.0-21.37_i386.deb (36.7 MiB)
    linux-image-extra-4.4.0-21-generic_4.4.0-21.37_ppc64el.deb (37.1 MiB)
    linux-image-extra-4.4.0-21-generic_4.4.0-21.37_s390x.deb (3.0 MiB)
    linux-source-4.4.0_4.4.0-21.37_all.deb (106.2 MiB)
    linux-tools-4.4.0-21-generic-lpae_4.4.0-21.37_armhf.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_amd64.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_arm64.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_armhf.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_i386.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_ppc64el.deb (1.8 KiB)
    linux-tools-4.4.0-21-generic_4.4.0-21.37_s390x.deb (1.8 KiB)
    linux-tools-4.4.0-21-lowlatency_4.4.0-21.37_amd64.deb (1.8 KiB)
    linux-tools-4.4.0-21-lowlatency_4.4.0-21.37_i386.deb (1.8 KiB)
    linux-tools-4.4.0-21-powerpc-e500mc_4.4.0-21.37_powerpc.deb (1.8 KiB)
    linux-tools-4.4.0-21-powerpc-smp_4.4.0-21.37_powerpc.deb (1.8 KiB)
    linux-tools-4.4.0-21-powerpc64-emb_4.4.0-21.37_powerpc.deb (1.8 KiB)
    linux-tools-4.4.0-21-powerpc64-smp_4.4.0-21.37_powerpc.deb (1.8 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_amd64.deb (658.1 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_arm64.deb (535.5 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_armhf.deb (514.7 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_i386.deb (648.0 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_powerpc.deb (543.4 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_ppc64el.deb (558.9 KiB)
    linux-tools-4.4.0-21_4.4.0-21.37_s390x.deb (558.6 KiB)
    linux-tools-common_4.4.0-21.37_all.deb (104.5 KiB)
    linux_4.4.0-21.37.diff.gz (10.3 MiB)
    linux_4.4.0-21.37.dsc (9.3 KiB)
    linux_4.4.0.orig.tar.gz (126.7 MiB)

**Comment by hrw** [comment]
They are built-in to kernel:

config-4.4.0-148-generic-aarch64:CONFIG_VIRTIO_BLK=y
config-4.4.0-148-generic-x86_64:CONFIG_VIRTIO_BLK=y
config-4.4.0-148-generic-aarch64:CONFIG_VIRTIO_NET=y
config-4.4.0-148-generic-x86_64:CONFIG_VIRTIO_NET=y
config-4.4.0-148-generic-aarch64:CONFIG_VIRTIO_PCI=y
config-4.4.0-148-generic-x86_64:CONFIG_VIRTIO_PCI=y
config-4.4.0-148-generic-aarch64:CONFIG_VFAT_FS=y
config-4.4.0-148-generic-x86_64:CONFIG_VFAT_FS=y
config-4.4.0-148-generic-aarch64:CONFIG_NLS_CODEPAGE_437=y
config-4.4.0-148-generic-x86_64:CONFIG_NLS_CODEPAGE_437=y
config-4.4.0-148-generic-aarch64:CONFIG_NLS_ISO8859_1=y
config-4.4.0-148-generic-x86_64:CONFIG_NLS_ISO8859_1=y

sr_mod:
config-4.4.0-148-generic-aarch64:CONFIG_BLK_DEV_SR=y
config-4.4.0-148-generic-x86_64:CONFIG_BLK_DEV_SR=y

sg:
config-4.4.0-148-generic-aarch64:CONFIG_CHR_DEV_SG=y
config-4.4.0-148-generic-x86_64:CONFIG_CHR_DEV_SG=y

cdrom is built-in due to sr_mod being built-in

qemu_fw_cfg: no idea where it could get from.

modprobe: module cdrom not found in modules.dep

**Comment by smoser** [comment]
Yeah... ideally the boot wouldn't show these messages.
So lets treat this as "don't try to modprobe modules that were known in the build to be built-in".

not sure immediately how i'd do that.

**Comment by hrw** [comment]
Maybe modprobe should just be muted. We know which kernel goes into image and we know that kernel parts we want are present.
