### ISSUE TITLE
test-boot: shutdown in manner that cirros-status is shown

### ISSUE THREAD

**Issue by smoser** [cirros-dev/cirros#39]
currently testboot just gives user-data that shuts sytem down with `poweroff -f`.

Because `cirros-userdata` (`S95-cirros-userdata`) is run before `cirros-status` (`S98-cirros-status`), we do not get the output of cirros-status, which is useful to show infrormation about cirros and the system.

It would be nice to get that information in the logs.  I had thought of this when I wanted to see which modules were loaded.

The easiest thing to do would be just have the user-data call cirros-status.  That would get what we want, but it would be nice to see the system "fully boot" to the `S99-logo` before shutting down.

**Comment by hrw** [comment]
One option is to use "timeout" command to run qemu. So it runs, do all and then gets killed.
