### ISSUE TITLE
Make released files available on github

### ISSUE THREAD

**Issue by smoser** [cirros-dev/cirros#5]
download.cirros-cloud.net will remain the canonical source, but we want to have files available on github.

The one necessary point is that I'd like to maintain 'streams' availability from http://download.cirros-cloud.net/streams/v1/index.json , and continue publishing that data for our github releases.

I did that previously with files hosted in a CDN and redirects on non-stream data from download.cirros-cloud.net/ to the other location.

**Comment by hrw** [comment]
Part one is done - we publish on github.

**Comment by smoser** [comment]
I just put this rule in .htaccess:

    RewriteRule ^(([0-9][.][0-9][.][0-9](_[^/*])?)/.*(.img|.gz|.xz|kernel|-initramfs))$ https://github.com/cirros-dev/cirros/releases/download/$1 [R=302]

That should (and tested a bit) redirect all download.cirros-cloud.net/X.Y.Z/ (or X.Y.Z_*) image content over to the github.  It seems working.

The goal is to keep the following on download.cirros-cloud.net:
  * metadata (md5/sha256sum files, streams/ content)
  * version/ information
And then re-direct all image content.
