### ISSUE TITLE
cirros 0.5.0 fails devstack/tempest testing in opendev Zuul CI jobs

### ISSUE THREAD

**Issue by yoctozepto** [cirros-dev/cirros#52]
Maciej proposed swapping cirros-0.4.0 with cirros-0.5.0 in devstack: https://review.opendev.org/711492
yet it looks like it's not really replaceable:
https://354104dbce37cf3de3e8-a3e8873768ae4ca0bf680cbb069c602c.ssl.cf1.rackcdn.com/711492/1/check/tempest-full-py3/188838b/testr_results.html
https://ff00fa925e62fbd157b6-5de95738ef5101e6146255f245e6c201.ssl.cf1.rackcdn.com/711492/1/check/neutron-tempest-linuxbridge/57cc3ad/testr_results.html
https://fc57f46eb4be1aeac42f-a8b09b46efefccdc6294594f5e7c68f1.ssl.cf2.rackcdn.com/711492/1/check/tempest-ipv6-only/a758f39/testr_results.html

At first I thought it was networking-related but after expanding the failures, it shows kernel panic:
[    6.464233] md: Waiting for all devices to be available before autodetect
[    6.465253] md: If you don't use raid, use raid=noautodetect
[    6.475404] md: Autodetecting RAID arrays.
[    6.476028] md: autorun ...
[    6.476485] md: ... autorun DONE.
[    6.480669] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    6.481773] Please append a correct "root=" boot option; here are the available partitions:
[    6.483743] 0b00         1048575 sr0 
[    6.483879]  driver: sr
[    6.485035] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    6.486470] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.3.0-26-generic #28~18.04.1-Ubuntu
[    6.487542] Hardware name: OpenStack Foundation OpenStack Nova, BIOS 1.10.2-1ubuntu1 04/01/2014
[    6.488849] Call Trace:
[    6.490607]  dump_stack+0x6d/0x95
[    6.491186]  panic+0xfe/0x2d4
[    6.491677]  mount_block_root+0x1f4/0x2db
[    6.492294]  ? set_debug_rodata+0x17/0x17
[    6.493201]  mount_root+0x38/0x3a
[    6.493735]  prepare_namespace+0x139/0x18e
[    6.494301]  kernel_init_freeable+0x245/0x26d
[    6.494890]  ? rest_init+0xb0/0xb0
[    6.495358]  kernel_init+0xe/0x110
[    6.495849]  ret_from_fork+0x35/0x40
[    6.497115] Kernel Offset: 0x39e00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[    6.498808] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---

**Comment by hrw** [comment]
We need to document that 128MB ram is required to boot 0.5.0 images.

**Comment by yoctozepto** [comment]
Relevant part:
[    3.194150] Trying to unpack rootfs image as initramfs...
[    3.201228] Initramfs unpacking failed: invalid magic at start of compressed archive

**Comment by hrw** [comment]
```
[    0.455288] Trying to unpack rootfs image as initramfs...
[    0.507535] swapper/0 invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[    0.508791] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.3.0-26-generic #28~18.04.1-Ubuntu
[    0.509789] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS ?-20190727_073836-buildvm-ppc64le-16.ppc.fedoraproject.org-3.fc31 04/01/2014
[    0.510640] Call Trace:
[    0.510640]  dump_stack+0x6d/0x95
[    0.510640]  dump_header+0x4f/0x200
[    0.510640]  out_of_memory+0x4c9/0x510
```
That's with 72MB of ram. So we recommend 128MB ram as minimum.

**Comment by hrw** [comment]
Minimal memory requirements are now listed in release notes. Thanks for reporting.

**Comment by yoctozepto** [comment]
Thanks, hrw.
