### ISSUE TITLE
cirros on exsi can't find eth0

### ISSUE THREAD

**Issue by tscswcn** [cirros-dev/cirros#60]
![image](https://user-images.githubusercontent.com/16184308/93001551-6054ed00-f562-11ea-8560-ad19889886e9.png)
cirros on exsi can't find eth0

**Comment by smoser** [comment]
I'm sure it depends on what network device you attach to the instance.
cirros includes drivers for e1000, ne2k-pci, 8139cp, pcnet32.

**Comment by tscswcn** [comment]
I  have convert cirros.img to cirros.vmdk, I run this cirros.vmdk with esxi host and got this error, do you have some comment, thanks! 
 or how to register these driver you provide within exsi host, thanks!

**Comment by smoser** [comment]
I'm not really familiar with vmware.  You'll need to just adjust the virtual hardware network devices that are presented to the machine. Perhaps some info at https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-AF9E24A8-2CFA-447B-AC83-35D563119667.html

**Comment by tscswcn** [comment]
thanks a lot!  I will try!

**Comment by tscswcn** [comment]
By the way,  it is OK in vmware workstatiion.  could you kindly tell me command we can use  in the cirros
lspci
dmesg
...... or some other command to debug? thanks a lot!

**Comment by smoser** [comment]
I suspect it should work fine in vmware  workstation or esxi if you give it
the right network device.  But, no, I don't have an example of it running
that I could collect info from.

**Comment by hrw** [comment]
We need to do release with it first before we close.

**Comment by hrw** [comment]
Please try 0.6.0

**Comment by hrw** [comment]
Closing due to lack of response
