### ISSUE TITLE
vmdk - Getting os not found on boot

### ISSUE THREAD

**Issue by rmssath** [cirros-dev/cirros#66]
Hi Team,

Converted the cirros img to vmdk
```qemu-img convert -f raw -O vmdk cirros-0.5.2-x86_64-disk.img cirros-0.5.2-x86_64-disk.vmdk```

While try to launch vm with vmdk, it shows **operating system not found** on boot.

**Comment by osfrickler** [comment]
The `cirros*.img` file should be in qcow2 format, not raw.
