### ISSUE TITLE
TCPDUMP support for cirros

### ISSUE THREAD

**Issue by sombrafam** [cirros-dev/cirros#72]
Cirros does not have a tcpdump utility. I have heard this complaint/need from a lot of people, and I'm raising this bug to see if there's any opposition to adding it to cirros or a reason on why it doesn't support it yet.

**Comment by NucciTheBoss** [comment]
Late to the party, but this does sound like something that should be considered for a future release of CirrOS.

However, before this feature can be added, it looks like CirrOS needs a new pipeline as indicated in #76.

**Comment by hrw** [comment]
Will be fixed with 0.6 release.

**Comment by hrw** [comment]
```
login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
cirros login: cirros
Password:
$ tcpdump --version
tcpdump version 4.99.1
libpcap version 1.10.1 (with TPACKET_V3)
$
```

**Comment by hrw** [comment]
0.6.0 is released
