### ISSUE TITLE
Populate the /etc/os-release file with cirros information

### ISSUE THREAD

**Issue by tas50** [cirros-dev/cirros#79]
Hi there. I'm trying to detect cirros containers within my product, and it's a bit tricky since there isn't information in the standard /etc/os-release on cirros. The containers are instead being identified as buildroot. Would it be possible to add the os and release in /etc/os-release so that tools that parse that file could more easily identify cirros containers?

Thanks,
Tim

**Comment by NucciTheBoss** [comment]
Will take a look at this for future releases.
