### ISSUE TITLE
Cirros doesn't retry metadata request on fail

### ISSUE THREAD

**Issue by mjozefcz** [cirros-dev/cirros#8]
Sometimes while Cirros fetch data from ec2metadata it is possible that request fails on various issues.  Recently in bug-report [1] I verified that HAProxy pass response related to request:

`GET /2009-04-04/meta-data/public-keys/0/openssh-key `

to Cirros in 0.2 sec but in fact curl claims that request times out. It ends with a Openstack Neutron gate failure. We don't know why it is happening.

To simply mitigate it I think we could simply add a '--retry 3' option to curl.

In OpenStack gates we identified a couple of similar bugs:
[1] https://bugs.launchpad.net/neutron/+bug/1856523
[2] https://bugs.launchpad.net/neutron/+bug/1836642
[3] https://bugs.launchpad.net/networking-ovn/+bug/1765545

**Comment by smoser** [comment]
`src/lib/cirros/ds/ec2` does '--max-time $TIMEOUT` (where TIMEOUT defaults to 10).

We can bump that up for sure, but you probably have issues in  your cloud somewhere that doing so will just mask.

**Comment by mjozefcz** [comment]
Hello.

The problem is not that the request only times out. The problem is more complicated. I would like to share here more how it looks.

We in OpenStack have CI/CD gating system that prevents us merging broken code. That includes several CI jobs (for now 34 jobs in Neutron master). A big subset of those jobs (about 32 now) are running OpenStack Tempest tests.
Tempest tests are tests that checks use-case scenarios on working cloud environment (devstack).

Those tempest tests for each test creates from 0 to 4 VMs (depends on scenario and on backend), and those tests are runned in parallel. That means in some cases we could have a few running VMs on given devstack.

Tempest tests are executed on devstack environments that are created on PublicCloud clouds. That means Openstack Fundation has dedicated aggregations only for OpenStack upstream gates (Example: OVH). In those terms it is frequent that CI jobs creates devstack VMs on the same hypervisors. That puts quite big load on those hypervisors. When I was working in OVH I saw hypervisor loads more than 50.  

In overall: for each change that we produce we run a several VMs running several tests inside that also create VMs. For that we use Cirros because its fast  and lightweight. If any of test of any job fails - we block the change. We have changes that needs to be 'recheck' several times in order to get merged just because of issue I'm describing here. Yes, we run a pretty decent workload there. But sometimes we have strange issues like described in bugs: [1] [2] [3]. This issue is related to Neutron Metadata.

The quick information how Neutron Metadata works:
https://github.com/cirros-dev/cirros/issues/8
https://tuantuluong.files.wordpress.com/2014/09/neutron-metadata-dhcp-agent.png

Essentially we have those functional unit blocks where VM is trying to reach its Metadata:

VM <-> Bridge <-> DHCP Namespace <->  HAPROXY <-> Neutron Metadata Agent <-> Nova Metadata Agent.

Request is 'proxy passed' a several times from VM to Nova Metadata Agent.

The issue described in [1] [2] [3] Is about we have a Cirros curl time out (more than 10 seconds), while HAPROXY claims that the answer for this request was served to instance in 0.2 seconds.
We don't know whats about and we were trying to find it out for several times [1] [2] [3].

For that problem we think that the load that tests put on hypervisor is decent, and its mainly related to it.

So the quick possible solution is to modify ec2metadata script to retry in case of transient error. Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408 or 5xx response code.

That would help us a lot. We believe on first retry the request described in [2] and [3] will pass and the tempest test would be able to login to cirros VM.

So please consider this change as not  a something that could hide our devstack cloud problem. We believe its mainly related to the load that tests are putting on the testing environment, and unfortunately it will be bigger in the future as we continuously add more tests.


[1] https://bugs.launchpad.net/neutron/+bug/1856523
[2] https://bugs.launchpad.net/neutron/+bug/1836642
[3] https://bugs.launchpad.net/networking-ovn/+bug/1765545

**Comment by danalsan** [comment]
Most of the distros use 20 retries so I believe that 3 could be a good compromise in order to not delay boot too long if the service wouldn’t be available. I’m ok with this change FWIW

**Comment by slawqo** [comment]
Yeah, I agree that retry could be good workaround. Please note that currently there are 20 retries on fetching instance_id (first call) and than there is no any retry for all other calls. I think that this could solve many random failures in OpenStack CI jobs.

**Comment by mjozefcz** [comment]
I retrigger Openstack jobs to run the code with --retry applied, all tempest tests ends with success:
https://review.opendev.org/#/c/682369/

That means the --retry really helps.

**Comment by smoser** [comment]
Ugh.  
I am OK with this change, but I really do think that you're just masking underlying architecture issues. 

I know from actual experience in cloud-init, cirros and openstack development that the metadata service causes huge amounts of load on the platform.  The right fix is to fix your metadata service, not to ignore the problem.

Unfortunately, people only linked to logs in the bugs rather than attaching, and all logs have been cleaned, so I cannot confirm my suspicion.

In these test runs, how long did it take cirros to boot? Lets say it took 2 minutes.  That means you booted virtual hardware (bios, kernel,disk, ....) in 2 minutes, but a HTTP couldn't be satisfied in 10 seconds?

**Comment by slawqo** [comment]
@smoser I agree that it should works better on OpenStack side but for now we don't know exactly why it happens like that from time to time. And also we know that we may experience some random issue due to overloaded infrastructure on which OpenStack CI is running. So such retries may help us with our gate stability in short term.
